
========================================
Test run command 1 : python3 a1_aanik.py 2018/01/01 1
--test passed--
Test run command 2 : python3 a1_aanik.py 2018/01/01 -1
--test passed--
Test run command 3 : python3 a1_aanik.py 2018/01/01 2
--test passed--
Test run command 4 : python3 a1_aanik.py --step 2018/01/01 3
--test passed--
Test run command 5 : python3 a1_aanik.py 2018/07/01 500
--test passed--
Test run command 6 : python3 a1_aanik.py 2018/99/01 2
Error: wrong month entered
--test failed--
---- expect: Error: wrong month entered
----  given: 
Test run command 7 : python3 a1_aanik.py 2018/01/99 2
Error: wrong day entered
--test failed--
---- expect: Error: wrong day entered
----  given: 
Test run command 8 : python3 a1_aanik.py 2018 2
Traceback (most recent call last):
  File "a1_aanik.py", line 246, in <module>
    print(dbda(sys.argv[1],sys.argv[2],0))
  File "a1_aanik.py", line 211, in dbda
    today = after(today)
  File "a1_aanik.py", line 107, in after
    valid_date(today)
  File "a1_aanik.py", line 38, in valid_date
    if len(today) != 10:
TypeError: object of type 'NoneType' has no len()
--test failed--
---- expect: Error: wrong date entered
----  given: 
Test run command 9 : python3 a1_aanik.py 2020/02/28 1
--test passed--
Test run command 10 : python3 a1_aanik.py 2020/03/01 -1
--test passed--
Test Results: {1: 1, 2: 1, 3: 1, 4: 1, 5: 1, 6: 0, 7: 0, 8: 0, 9: 1, 10: 1}
Total test run marks:  33.599999999999994
Total marks for script (max. 48): 33.599999999999994
